### ISSUE TITLE
SOM to Pull match rate decreased. Do we need to tweak calc settings more? Or, what are next steps?

### ISSUE THREAD

**Issue by markjam33** [jturner65/StraffordSOMVis#4]
With the latest project build, the match rate between the SOM PerProd Suggestions files and Puller results using the test products (in ProductsToMap_Test.txt) has decreased over the previous build, using the default calc settings and identical SOM settings, from ~89.5% to ~81%. Match rate against actual orders for the same set of products has decreased, as well, from ~99% to ~95.7%. At the same time, the number of suggestions per product has seemed to shrink, ranging from 151,068 (for product id 7875) to 577,124 (for product id 7815); with the previous project build, this range was from 205,652 (for product id 7875) to 824,405 (for product id 7757).

**Comment by markjam33** [comment]
Next looking at top 20,000 suggestions to analyze match rate.

**Comment by jturner65** [comment]
are you just looking at customers?  or both customers and true prospects?

**Comment by markjam33** [comment]
I am looking at both customers and prospects.

Looking at top 20,000 suggestions for all test products (sorted in ascending order on the "error" column), the mean order match rate sinks to ~36.6%. With the same subset, the match rate to the Puller results for all test products sinks to ~27.1%.

I will test just customers next.

**Comment by markjam33** [comment]
That said, should the intersect between what our current processes are creating and what the SOM is suggesting be that far apart? This would indicate that our existing processes are pulling very low quality segments. This may very well be true, but it's going to be a VERY hard sell to those who are convinced otherwise...

**Comment by markjam33** [comment]
I randomly sampled prospects (oid starting with "PR_") from the PerProd Suggestions file for 7749, (tagged with 283 and 362, both Loan Doc-related JPs), and only a fraction of my sample had any source data whatsoever with Loan Doc-related JPs of any sort.

Also, I noticed that very few customers (oid starting with "US_") are present toward the top of the file; most of these are stacked toward the bottom. Am I looking at the data wrong? Should the strongest candidates be toward the top, with high confidence and low distance?

**Comment by jturner65** [comment]
Few things
1) it is a good thing that, with around 1/2 as many proposals, the success rate has changed so little.  This suggests an improvement in accuracy.

2) we dont' change anything until we are sure there are no bugs in either process.  Some of the nature of these results suggests something may be being done wrong.  There very well may be something wrong with how my proposals are being mapped, or saved.

I will look through these results and verify things.

**Comment by jturner65** [comment]
Let me also explain my current expectations.  
1) I expect all customers to match with high success.  This is because these folks are responsible for training the map, and therefore the map's suggested product matching should be high.  I think we are doing OK here - remember, we are matching a certain % of customers to the puller, but we are also providing others that the puller may miss that we currently have no way to verify.

2) I expect prospects to map with much less success.  This is because the TP recs only use the same ftr vector calc used by the customers in the comparison calculation (i.e. TP past behavior in product JPs).  I felt it was necessary to determine what the performance of this vector was for the TPs in order to determine how best to proceed.

I understand there might be some disappointment and frustration that these results are not yet ready for prime time, but in my defense :) there hasn't been much interactive refinement going on with respect to the results.  

To put it in perspective, in the past when I have implemented these kinds of systems before, once the implementation was complete (and covered all originating/source data) we would conduct around 7 or 8 proposal experiments before we would put this new system online, where a proposal experiment would consist of a map is queried for proposals, these are compared to existing systems' results or some other ground truth, they are investigated for issues and the code is then refined as necessary.

This last test is only our 2nd go around using the source event data (i.e. a "complete implementation", at least in data terms).  This is why i would like to hold off on any kind of calc mods until we are certain all data and all functionality is working as expected, both in the system and in the verification network.  While I am certainly not expecting this to take 7 or 8 iterations, i do expect a few cycles before we move on to tweaking.

I am hoping this process will speed up soon, but unfortunately I am just 1 hand clapping without your testing involvement :).

**Comment by markjam33** [comment]
Understood. Both of us are constrained by bandwidth. Honestly, the last two weeks are the first in a long time I've had to dedicate significant time to work on this project. My time is split between several massive projects, and they ebb and flow in terms of priority based on demands from the rest of the business. And I don't really have anyone else I can throw at this problem, largely because no one else has any time, either. This is the problem with having a small, underresourced team and a culture of impatience.

**Comment by markjam33** [comment]
So, how can I help speed up the process? I am making myself available as much as possible in the immediate future, but I can guarantee that the present window of availability is going to shut soon, because someone will come up with an "emergency" that has to be handled NOW and I will be redirected, in spite of my best efforts. What suggestions would you have on some specific ways I can analyze these result files that will put us on the correct track to solving the issues?

**Comment by markjam33** [comment]
Are these spot checks and match rate checks meaningful enough? Should I be looking at other statistical methods to examine the output?

**Comment by jturner65** [comment]
Yes they are, at least for me, although until the expanded comparison vector handling is implemented it probably doesn't add much now.  It's hard for me to say more to guide you just yet, until we've performed another experiment or two to understand where we stand w/respect to the true prospects.  

As it is now, the next big thing i'm working on is going to be the method of building the comparison vector for the true prospects. When this is in it will require testing, and I am going to write some quick code that will save both the ftr vectors and the alt comp vectors for all the prospects, to a csv so we can see what exactly is being built. 

The biggest thing we need to have now, i think, (along with this functionality) is some mechanism to verify the results of the calculations, as well as a way to verify the products.  Sometimes when i display "current product" almost the entire map will light up, denoting some non-zero wt in many of the ftrs that a product with that particular jp would otherwise ignore.  This tells me there's some noise or error in some of the products' mapping vectors, or else there might be products that are getting poorly built.  I also want to verify the integrity of these.

**Comment by markjam33** [comment]
With the latest build (which appears for the moment to be disregarding true prospects), the match rate to a Puller list is ~21%. I will investigate some of the non-matches to see if patterns emerge as to sorts of customers being suggested. From a count perspective, the SOM is exporting between 8x and 10x more suggestions than our puller does. Again, the "big deal" about this is there are significant potential negative ramifications to sending this volume, so we need to be sure we are honing this to only the very best candidates.
