### ISSUE TITLE
Suggestions for CLI arguments.

### ISSUE THREAD

**Issue by markjam33** [jturner65/StraffordSOMVis#5]
As promised, here are the CLI arguments I think would be most useful to pass to the headless version of the project. Preferably, the tool would accept either standard Windows-style "/switch" arguments or POSIX long-form arguments: "--argument=value", but if you want to use one style for simplicity, I prefer the POSIX style, perhaps with single-dash . I don't mind if the long-form arguments use the single or double-dash delimiters); double-dash for long-form arguments are more standard, but both are fairly common when a tool only accepts long-form arguments. I don't think short-form POSIX arguments are necessary (e.g. "-h" vs. "--help"). There may be a Java library that would simplify this -- I know there are similar libraries for other languages.

The arguments (shown as "--POSIX or /Windows"):
--help or /help: List a brief description of all arguments.

Settings/config arguments (these would override any relative paths or config-file-based paths):
--projectpath=[path] or /projectpath [path]: Use the supplied path for the directory containing config, output, and data files

--sompath=[path] or /sompath [path]: Path to the somoclu executable.

Execution arguments (these correspond to the execution buttons in the UI):
--loadAllRawCSVs or /loadAllRawCSVs

--recalcFeatures or /recalcFeatures

--trainData or /trainData

--prospects or /prospects

--somConfig or /somConfig

--allBuildMap or /allBuildMap

--prebuiltMap or /prebuiltMap

--buildSOM or /buildSOM

--mapProspectBMUs or /mapProspectBMUs

--saveProducts or /saveProducts

I **think** these are all of the necessary arguments. You may know more about whether these can be consolidated or not; I want to make sure we can run the CLI tool with about the same level of execution granularity that the UI currently provides, because I can anticipate the need to be able to run these processes independently sometimes, as we currently can. I think the various controls for, i.e. somoclu args or JP feature shown, do not need correlatives in the CLI tool.

**Comment by jturner65** [comment]
great!  i'll get on these - they'll be a slight divergence from what i am using currently, but easy enough to implement.  I found a very nice arg parser that is designed to work like argparse in python.

**Comment by markjam33** [comment]
May I make one additional request? It would be helpful to be able to send the PerProdSuggestions files to a different location via a CLI argument. This isn't critical, and if it would be a lot of work, we can forego. If it is trivial to implement, then the argument could be something like the following:

--productPath=[path] or /productPath [path]

I'm just thinking ahead to how the application would be used in production, and the ability to define on run where the PerProdSuggestions get saved to would be immensely helpful.

**Comment by jturner65** [comment]
That's a good idea.  i'll work on that too.

**Comment by jturner65** [comment]
Some of these are only useful in the UI program (like recalcFeatures - this is only to recalculate data in memory).  Since the command line execution is a complete process, these are superfluous.  The number of command line args will be minimal, actually, because many of the functions that are separate in the UI by necessity need to be coalesced into single processes in the command line version.

how about i just use posix-style delimiters.  -,-- with - prefixing a single letter and -- prefixing a word (-h , --help).  if you'd rather i not do that, that's fine.  

also, i currently have a different config and data directory (as per an earlier conversation).  I'm also setting the SOM to reside in the data directory under the SOM subdirectory - this can be easily modified by a link in linux, i would imagine, or by adding the SOM to the system path.

**Comment by markjam33** [comment]
Using only POSIX-style delimiters is fine. We will be running on Linux in production.
